### ISSUE TITLE
The use of WhatsApp excludes some users

### ISSUE THREAD

**Issue by joaompinto** [kind-in-open-source/kind-in-open-source.github.io#1]
I had conversations with some friends which are unwilling to participate int he project as long it is based on WhatsApp considering:

1. It is not opensource
2. It provides information to "Meta" for business purposes which can be considered abusive of privacy rights

The use of WA was pragmatic, the community capabilities are unique (not available in Telegram) and it is more widely deployed than WA.

This issue should be used to track concerns about the current option and suggest alternatives, understanding that there is no perfect option.

**Comment by nico-hen** [comment]
I use [Signal](https://github.com/signalapp/Signal-Android) a lot. Works and I show my appreciation for their work by annual donations.

**Comment by joaompinto** [comment]
I will check Signal, most likely this issue will result in a list of options with pros/cons .
Thanks

**Comment by joaompinto** [comment]
Hum, Signal forces a pin to be added, I can see all sort of the issues with pins being lost, considering that the project is focused on  non sensitive comms I would say it's overkill :\

**Comment by albertominetti** [comment]
Most of the people on Signal are not on whatsapp, and viceversa. The will be always someone that does not use the specific app.

**Comment by joaompinto** [comment]
@albertominetti , it's a complex problem. another advantage of WhatsApp is that for desktop it does not require any installation.
The ideal application would be:
0. have the features we need (community groups)
1. web based for desktop
2. light to install
3. phone based to reduce spam/bots
4. managed under an organization with a strong privacy policy

Telegram fails on 0 :(

**Comment by joaompinto** [comment]
Closing this bug since we moved to Telegram
